export const CASH_IN_API_URL = process.env.NEXT_PUBLIC_CASH_IN_API_URL;
export const CASH_OUT_API_URL_NATURAL = process.env.NEXT_PUBLIC_CASH_OUT_API_URL_NATURAL;
export const CASH_OUT_API_URL_LEGAL = process.env.NEXT_PUBLIC_CASH_OUT_API_URL_LEGAL;